"""Generates plugins/common/ui/Theme.h from design/tokens.json.

    python design/gen_theme.py           # write Theme.h
    python design/gen_theme.py --check   # exit 1 if Theme.h is out of date (CTest / CI)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT = ROOT / "plugins" / "common" / "ui" / "Theme.h"


def argb(value: str) -> str:
    value = value.strip()
    m = re.fullmatch(r"#([0-9a-fA-F]{6})", value)
    if m:
        return "0xff" + m.group(1).lower()
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)", value)
    if m:
        r, g, b = (int(m.group(i)) for i in range(1, 4))
        a = round(float(m.group(4)) * 255)
        return f"0x{a:02x}{r:02x}{g:02x}{b:02x}"
    raise ValueError(f"unsupported colour: {value}")


def generate() -> str:
    t = json.loads(TOKENS.read_text(encoding="utf-8"))
    light, dark = t["color"]["light"], t["color"]["dark"]
    if light.keys() != dark.keys():
        raise ValueError("light and dark palettes must define the same tokens")
    names = list(light.keys())

    out = [
        "// GENERATED by design/gen_theme.py from design/tokens.json - do not edit by hand.",
        "#pragma once",
        "",
        "#include <juce_graphics/juce_graphics.h>",
        "",
        "namespace hearaside::theme {",
        "",
        "struct Palette {",
    ]
    out += [f"    juce::Colour {n};" for n in names]
    out += ["};", ""]
    for label, pal in (("light", light), ("dark", dark)):
        out.append(f"inline const Palette& {label}() {{")
        out.append("    static const Palette p {")
        out += [f"        juce::Colour({argb(pal[n])}u),   // {n}" for n in names]
        out.append("    };")
        out.append("    return p;")
        out.append("}")
        out.append("")
    for group in ("radius", "space", "type", "glass", "motion"):
        out.append(f"namespace {group} {{")
        for k, v in t[group].items():
            out.append(f"constexpr float {k} = {float(v)!r}f;")
        out.append("}")
        out.append("")
    out.append("} // namespace hearaside::theme")
    return "\n".join(out) + "\n"


def main() -> int:
    text = generate()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date - run python design/gen_theme.py")
            return 1
        print("Theme.h is in sync with tokens.json")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
