"""Generates plugins/common/ui/Theme.h and web/site/src/styles/tokens.css from design/tokens.json.

    python design/gen_theme.py           # write Theme.h
    python design/gen_theme.py --check   # exit 1 if Theme.h is out of date or a text colour fails contrast (CTest / CI)
    python design/gen_theme.py --contrast  # only the WCAG contrast check (docs/ux-roadmap.md, 6.2)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
OUT = ROOT / "plugins" / "common" / "ui" / "Theme.h"
CSS_OUT = ROOT / "web" / "site" / "src" / "styles" / "tokens.css"


def argb(value: str) -> str:
    value = value.strip()
    m = re.fullmatch(r"#([0-9a-fA-F]{6})", value)
    if m:
        return "0xff" + m.group(1).lower()
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)", value)
    if m:
        r, g, b = (int(m.group(i)) for i in range(1, 4))
        a = round(float(m.group(4)) * 255)
        return f"0x{a:02x}{r:02x}{g:02x}{b:02x}"
    raise ValueError(f"unsupported colour: {value}")


def generate() -> str:
    t = json.loads(TOKENS.read_text(encoding="utf-8"))
    light, dark = t["color"]["light"], t["color"]["dark"]
    if light.keys() != dark.keys():
        raise ValueError("light and dark palettes must define the same tokens")
    names = list(light.keys())

    out = [
        "// GENERATED by design/gen_theme.py from design/tokens.json - do not edit by hand.",
        "#pragma once",
        "",
        "#include <juce_graphics/juce_graphics.h>",
        "",
        "namespace hearaside::theme {",
        "",
        "struct Palette {",
    ]
    out += [f"    juce::Colour {n};" for n in names]
    out += ["};", ""]
    for label, pal in (("light", light), ("dark", dark)):
        out.append(f"inline const Palette& {label}() {{")
        out.append("    static const Palette p {")
        out += [f"        juce::Colour({argb(pal[n])}u),   // {n}" for n in names]
        out.append("    };")
        out.append("    return p;")
        out.append("}")
        out.append("")
    for group in ("radius", "space", "type", "glass", "motion", "layout"):
        out.append(f"namespace {group} {{")
        for k, v in t[group].items():
            if k.startswith("$"):
                continue
            out.append(f"constexpr float {k} = {float(v)!r}f;")
        out.append("}")
        out.append("")
    out.append("} // namespace hearaside::theme")
    return "\n".join(out) + "\n"


def css_colour(value: str) -> str:
    return value.strip()


def generate_css() -> str:
    """tokens.css for the website: the same palette as the plug-ins, as CSS variables, plus the
    Tailwind v4 @theme mapping so utility classes use the tokens (no raw colours in classNames)."""
    t = json.loads(TOKENS.read_text(encoding="utf-8"))
    light, dark = t["color"]["light"], t["color"]["dark"]
    out = ["/* GENERATED by design/gen_theme.py from design/tokens.json - do not edit by hand. */", ""]
    out.append(":root {")
    out += [f"  --hs-{n}: {css_colour(v)};" for n, v in light.items()]
    out.append("  color-scheme: light;")
    out.append("}")
    out.append("")
    dark_vars = [f"  --hs-{n}: {css_colour(v)};" for n, v in dark.items()]
    out.append(':root[data-theme="dark"] {')
    out += dark_vars
    out.append("  color-scheme: dark;")
    out.append("}")
    out.append("")
    out.append("@media (prefers-color-scheme: dark) {")
    out.append('  :root:not([data-theme="light"]) {')
    out += ["  " + v for v in dark_vars]
    out.append("    color-scheme: dark;")
    out.append("  }")
    out.append("}")
    out.append("")
    out.append("@theme inline {")
    out += [f"  --color-{n}: var(--hs-{n});" for n in light.keys()]
    for k, v in t["radius"].items():
        if not k.startswith("$"):
            out.append(f"  --radius-{k}: {v}px;")
    out.append("  --font-sans: 'Anuphan', system-ui, -apple-system, 'Segoe UI', sans-serif;")
    out.append("}")
    return "\n".join(out) + "\n"


def parse_colour(value: str):
    v = argb(value)
    n = int(v, 16)
    return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255, ((n >> 24) & 255) / 255]


def over(top, bottom):
    a = top[3]
    return [top[i] * a + bottom[i] * (1 - a) for i in range(3)] + [1.0]


def luminance(c) -> float:
    f = lambda x: x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4
    return 0.2126 * f(c[0]) + 0.7152 * f(c[1]) + 0.0722 * f(c[2])


def contrast_ratio(a, b) -> float:
    la, lb = luminance(a), luminance(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)


def contrast_problems() -> list:
    """WCAG contrast of every text token on every background, both themes (section 6.2)."""
    t = json.loads(TOKENS.read_text(encoding="utf-8"))
    rules = t["contrast"]
    problems = []
    for mode in ("light", "dark"):
        pal = {k: parse_colour(v) for k, v in t["color"][mode].items()}

        def layer(stack: str):
            names = stack.split(">")
            colour = pal[names[-1]]
            for n in reversed(names[:-1]):
                colour = over(pal[n], colour)
            return colour

        pairs = [(fg, bg) for fg in rules["text"] for bg in rules["backgrounds"]] + [tuple(p) for p in rules["pairs"]]
        for fg, bg in pairs:
            back = layer(bg)
            ratio = contrast_ratio(over(pal[fg], back), back)
            if ratio < rules["minRatio"]:
                problems.append(f"{mode}: {fg} on {bg} = {ratio:.2f}:1 (needs {rules['minRatio']}:1)")
    for name in rules["disabledOnly"]:
        if name in rules["text"]:
            problems.append(f"{name} is listed as disabled-only and as text")
    return problems


def main() -> int:
    text = generate()
    if "--contrast" in sys.argv or "--check" in sys.argv:
        problems = contrast_problems()
        for p in problems:
            print("contrast:", p)
        if problems:
            return 1
        print("contrast: every text token reaches the minimum ratio in both themes")
        if "--contrast" in sys.argv:
            return 0
    css = generate_css()
    if "--check" in sys.argv:
        for path, want in ((OUT, text), (CSS_OUT, css)):
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current.replace("\r\n", "\n") != want:
                print(f"{path.relative_to(ROOT)} is out of date - run python design/gen_theme.py")
                return 1
        print("Theme.h and tokens.css are in sync with tokens.json")
        return 0
    for path, want in ((OUT, text), (CSS_OUT, css)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
