// GENERATED by design/gen_theme.py from design/tokens.json - do not edit by hand.
#pragma once

#include <juce_graphics/juce_graphics.h>

namespace hearaside::theme {

struct Palette {
    juce::Colour paper;
    juce::Colour grid;
    juce::Colour ink;
    juce::Colour onInk;
    juce::Colour ink2;
    juce::Colour graphite;
    juce::Colour offFg;
    juce::Colour muted;
    juce::Colour glass;
    juce::Colour glassEdge;
    juce::Colour inset;
    juce::Colour offBg;
    juce::Colour chipBg;
    juce::Colour hairline1;
    juce::Colour hairline2;
    juce::Colour hairline3;
    juce::Colour rowOnEdge;
    juce::Colour switchOff;
    juce::Colour sliderRail;
    juce::Colour shadow;
    juce::Colour blobWarm;
    juce::Colour blobCool;
    juce::Colour trackShade1;
    juce::Colour trackShade2;
    juce::Colour trackShade3;
    juce::Colour trackShade4;
    juce::Colour trackShade5;
    juce::Colour danger;
    juce::Colour dangerBg;
    juce::Colour warn;
    juce::Colour warnBg;
    juce::Colour ok;
    juce::Colour menuBg;
    juce::Colour sheet;
    juce::Colour thumb;
    juce::Colour scrollThumb;
    juce::Colour scrollThumbHover;
    juce::Colour scrollThumbActive;
    juce::Colour focusRing;
};

inline const Palette& light() {
    static const Palette p {
        juce::Colour(0xfff3f3f1u),   // paper
        juce::Colour(0x0d181818u),   // grid
        juce::Colour(0xff181818u),   // ink
        juce::Colour(0xffffffffu),   // onInk
        juce::Colour(0xff3e3e3au),   // ink2
        juce::Colour(0xff5a5a56u),   // graphite
        juce::Colour(0xff55554fu),   // offFg
        juce::Colour(0xff8a8a84u),   // muted
        juce::Colour(0x9effffffu),   // glass
        juce::Colour(0xd9ffffffu),   // glassEdge
        juce::Colour(0xe6f0f0edu),   // inset
        juce::Colour(0xccffffffu),   // offBg
        juce::Colour(0xb8ffffffu),   // chipBg
        juce::Colour(0x0d181818u),   // hairline1
        juce::Colour(0x14181818u),   // hairline2
        juce::Colour(0x1f181818u),   // hairline3
        juce::Colour(0x38181818u),   // rowOnEdge
        juce::Colour(0x2e181818u),   // switchOff
        juce::Colour(0x24181818u),   // sliderRail
        juce::Colour(0x0f181818u),   // shadow
        juce::Colour(0x6b706a60u),   // blobWarm
        juce::Colour(0x33282826u),   // blobCool
        juce::Colour(0xff181818u),   // trackShade1
        juce::Colour(0xff5a5a56u),   // trackShade2
        juce::Colour(0xff8c8c86u),   // trackShade3
        juce::Colour(0xffb4b4aeu),   // trackShade4
        juce::Colour(0xffd2d2ccu),   // trackShade5
        juce::Colour(0xffb42318u),   // danger
        juce::Colour(0xffb42318u),   // dangerBg
        juce::Colour(0xffb54708u),   // warn
        juce::Colour(0x14b54708u),   // warnBg
        juce::Colour(0xff0f7553u),   // ok
        juce::Colour(0xffffffffu),   // menuBg
        juce::Colour(0xf7fafaf8u),   // sheet
        juce::Colour(0xffffffffu),   // thumb
        juce::Colour(0x24181818u),   // scrollThumb
        juce::Colour(0x4c181818u),   // scrollThumbHover
        juce::Colour(0x80181818u),   // scrollThumbActive
        juce::Colour(0x1a181818u),   // focusRing
    };
    return p;
}

inline const Palette& dark() {
    static const Palette p {
        juce::Colour(0xff151514u),   // paper
        juce::Colour(0x0bffffffu),   // grid
        juce::Colour(0xffededeau),   // ink
        juce::Colour(0xff151514u),   // onInk
        juce::Colour(0xffcfcfcau),   // ink2
        juce::Colour(0xffa3a39du),   // graphite
        juce::Colour(0xffababa4u),   // offFg
        juce::Colour(0xff6e6e69u),   // muted
        juce::Colour(0x9e262624u),   // glass
        juce::Colour(0x1affffffu),   // glassEdge
        juce::Colour(0x0effffffu),   // inset
        juce::Colour(0x0dffffffu),   // offBg
        juce::Colour(0x0fffffffu),   // chipBg
        juce::Colour(0x0fffffffu),   // hairline1
        juce::Colour(0x1affffffu),   // hairline2
        juce::Colour(0x29ffffffu),   // hairline3
        juce::Colour(0x4cffffffu),   // rowOnEdge
        juce::Colour(0x33ffffffu),   // switchOff
        juce::Colour(0x29ffffffu),   // sliderRail
        juce::Colour(0x4c000000u),   // shadow
        juce::Colour(0x4c968a76u),   // blobWarm
        juce::Colour(0x385a5a56u),   // blobCool
        juce::Colour(0xffededeau),   // trackShade1
        juce::Colour(0xffb9b9b3u),   // trackShade2
        juce::Colour(0xff8c8c86u),   // trackShade3
        juce::Colour(0xff66665fu),   // trackShade4
        juce::Colour(0xff4a4a45u),   // trackShade5
        juce::Colour(0xffff8a80u),   // danger
        juce::Colour(0xffc8322fu),   // dangerBg
        juce::Colour(0xfffdb022u),   // warn
        juce::Colour(0x1afdb022u),   // warnBg
        juce::Colour(0xff3ccb7fu),   // ok
        juce::Colour(0xff242422u),   // menuBg
        juce::Colour(0xf71e1e1du),   // sheet
        juce::Colour(0xffededeau),   // thumb
        juce::Colour(0x24ffffffu),   // scrollThumb
        juce::Colour(0x4cffffffu),   // scrollThumbHover
        juce::Colour(0x80ffffffu),   // scrollThumbActive
        juce::Colour(0x29ffffffu),   // focusRing
    };
    return p;
}

namespace radius {
constexpr float card = 22.0f;
constexpr float header = 20.0f;
constexpr float row = 14.0f;
constexpr float primary = 14.0f;
constexpr float small = 12.0f;
constexpr float meter = 3.0f;
}

namespace space {
constexpr float hubPad = 20.0f;
constexpr float trackPad = 16.0f;
constexpr float cardGap = 16.0f;
constexpr float rowGap = 8.0f;
}

namespace type {
constexpr float wordmark = 17.0f;
constexpr float h1 = 20.0f;
constexpr float h2 = 17.0f;
constexpr float bigNumber = 22.0f;
constexpr float trackName = 14.0f;
constexpr float button = 13.0f;
constexpr float caption = 12.0f;
constexpr float micro = 10.0f;
}

namespace glass {
constexpr float blur = 18.0f;
constexpr float alphaDefault = 0.62f;
constexpr float alphaMin = 0.35f;
constexpr float alphaMax = 0.95f;
}

namespace motion {
constexpr float switchMs = 160.0f;
constexpr float fadeMs = 120.0f;
constexpr float meterFps = 30.0f;
}

namespace layout {
constexpr float compactBelow = 760.0f;
constexpr float wideAbove = 1180.0f;
constexpr float hysteresis = 24.0f;
constexpr float compactPad = 12.0f;
constexpr float hubMinW = 420.0f;
constexpr float hubMinH = 460.0f;
constexpr float trackMinW = 380.0f;
constexpr float trackMinH = 460.0f;
constexpr float appMinW = 380.0f;
constexpr float appMinH = 400.0f;
constexpr float panelMargin = 32.0f;
constexpr float screenFit = 0.85f;
constexpr float rowH = 56.0f;
constexpr float rowNarrowH = 104.0f;
constexpr float minTarget = 32.0f;
}

} // namespace hearaside::theme
